#define SFX_BASS	0
#define SFX_CRASH	1
#define SFX_HANDCLAP	2
#define SFX_HIHAT_CLOSED	3
#define SFX_HIHAT_OPENED	4
#define SFX_RIDE	5
#define SFX_RIM	6
#define SFX_SNARE	7
#define SFX_TOM_HIGH	8
#define SFX_TOM_LOW	9
#define SFX_TOM_MID	10
#define MSL_NSONGS	0
#define MSL_NSAMPS	11
#define MSL_BANKSIZE	11
